"""add user group, add BookRequest

Revision ID: 787e0b375062
Revises: 939af2c2c9ea
Create Date: 2025-02-16 12:56:48.250739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '787e0b375062'
down_revision: Union[str, None] = '939af2c2c9ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Fixed PostgreSQL compatibility: Use explicit String types instead of AutoString
    op.create_table('bookrequest',
    sa.Column('asin', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('authors', sa.String(), nullable=False),
    sa.Column('narrators', sa.String(), nullable=False),
    sa.Column('cover_image', sa.String(), nullable=True),
    sa.Column('user_username', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_username'], ['"user".username'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asin')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group', sa.String(), server_default='untrusted', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('group')

    op.drop_table('bookrequest')
    # ### end Alembic commands ###
